### ISSUE TITLE
RSS Feed of New Jokes

### ISSUE THREAD

**Issue by adamgriffis** [sylturner/Jokels#11]

**Comment by adamgriffis** [comment]
I'm an idiot, I just found it.  We might want to stick a link on the main page somewhere (and however you make it so FF and chrome have that atom icon?) so it's clear there's a feed.

**Comment by sylturner** [comment]
Hah yeah. That's a good idea. To add the autodiscovery thing, you just add this to the application.html.erb:
 `<link rel="alternate" type="application/rss+xml"  href="http://jokels.com/feed" title="Jokels Feed">`

You can also add a link with the icon in the footer somewhere, too.

**Comment by sylturner** [comment]
Actually, it might be `application/atom+xml` for the type. I'm not sure.
