### ISSUE TITLE
Add a share to facebook link instead of the "like" link.

### ISSUE THREAD

**Issue by adamgriffis** [sylturner/Jokels#22]
I think the problem is that you can't like a link that you're not currently looking at?  Either way, all likes just end up pointing to Jokels.com instead of the specific joke.  We could just make it share it to your account.

**Comment by sylturner** [comment]
Here's some stuff about the "Like" button: https://developers.facebook.com/docs/reference/plugins/like/
And the "Send" button: https://developers.facebook.com/docs/reference/plugins/send/
