### ISSUE TITLE
Find somewhere to stick the Joke tooltip in the actual Joke page

### ISSUE THREAD

**Issue by adamgriffis** [sylturner/Jokels#29]
There's info in the Jokel tooltip that we don't actually show on the Joke's page.  It'd be nice if we could stick this on the Joke page somewhere (maybe a "?" that when hovered over gives the Jokel tooltip? Probably could use more thought).

**Comment by sylturner** [comment]
You could use an icon like [this one](http://i.imgur.com/zjTW0.png) that you hover over for more info.
