### ISSUE TITLE
Kiosk Mode

### ISSUE THREAD

**Issue by adamgriffis** [sylturner/Jokels#34]
A cool feature would be if we could automate going through jokes and looking at the alternate punchlines so Jokels could just be running on a screen like at the Office or the VT?

**Comment by sylturner** [comment]
Awesome idea

**Comment by adamgriffis** [comment]
Gonna leave this open for a while until we can discuss it and talk about some possible changes.

**Comment by sylturner** [comment]
- `Is there a better way to brand this than "Kiosk Mode?"` 
  - Autojokels?
- 7.5 seconds is a good default. A cool UI idea would be a slider thing for refresh speed. 
- `Should we minimize the UI at all to communicate that it's in kiosk mode?`
  - I don't know if that's necessary, but a 'full screen' mode might be cool. i.e. the header/footer are gone, and it has the 'jokels' logo in the bottom right or something.
- Unless the UI changes significantly in kiosk mode, I think showing Qtips automatically would look strange.
